name: pet_track
description: A Flutter app for tracking and reuniting lost pets with their families.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_secure_storage: ^8.0.0 # for storing JWT token

  
  # State Management
  provider: ^6.1.1
  
  # UI & Styling
  flutter_svg: ^2.0.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # HTTP & API
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Camera & Image
  image_picker: ^1.1.2  
  cross_file: ^0.3.4+2
  camera: ^0.10.5+5
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.1

  # Firebase (only auth required)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
